### ISSUE TITLE
Fix JSDoc GitHub Action

### ISSUE THREAD

**Issue by bimai25** [cse110-sp23-group4/cse110-sp23-group4#105]
The JSDocs GitHub action is not generating output HTML files

**Comment by abijitj** [comment]
There are deprecated methods in the [andstor repo](https://github.com/andstor/jsdoc-action).  This is likely what is causing the documentation to not be generated. So, I think we have two options...

1. We manually generate JSdocs (perhaps every few days) using one command.

2. Automatically generate JSdocs using command line arguments through GitHub actions. This could be a bit tricky and time-consuming to get fully functioning.

**Comment by bimai25** [comment]
Malcolm said other groups have gotten the JSDocs action going. We can ask Malcolm for help with this

**Comment by abijitj** [comment]
That's great! We should do that as soon as possible.

**Comment by abijitj** [comment]
I think Brandon had already tried running jsdocs and deploying from the same document. It didn't work I believe? 

But Brandon and I asked Malcolm for help and he suggested we create a custom action that runs jsdocs and then commits those changes (also gave us a sequence of commands). We will keep everyone updated on our progress in implementing that.
