### ISSUE TITLE
Saved Readings Page Tests 

### ISSUE THREAD

**Issue by abijitj** [cse110-sp23-group4/cse110-sp23-group4#191]
Tests for the saved readings page. This should test only functionality that is independent of the fortunate generation page (i.e. functionality that you can initiate starting from this page)

**Comment by bimai25** [comment]
@abijitj has this project being completed with #210 ?

**Comment by abijitj** [comment]
No, not yet. Michi and I going to write a few more tests for this page.

**Comment by bimai25** [comment]
Done with #210
